### ISSUE TITLE
Issue in signing in drive

### ISSUE THREAD

**Issue by Rithvikailas** [RonLek/ALPR-and-Identification-for-Indian-Vehicles#4]
Can I get the current  drive password of the mail id: sih2020rm@gmail.com ?

**Comment by RonLek** [comment]
@Rithvikailas please read this [comment](https://github.com/RonLek/ALPR-and-Identification-for-Indian-Vehicles/issues/2#issuecomment-946830322). You **do not** require access to the drive.
